-- Initial collection from Natalie’s supplied messages. Prices are unset; verify stock before sales.
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('green-matcha-set','Matcha bowl & whisk holder','Tea rituals','A green glazed bowl with a pouring spout, paired with a matching whisk holder.',null,0,1.08,null,'BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/green-matcha-bowl-whisk-holder-set.jpg", "alt": "Matcha bowl & whisk holder"}, {"src": "/products/green-matcha-bowl-whisk-holder-set-angle.jpg", "alt": "Matcha bowl and whisk holder, alternate view"}]'::jsonb,'mint',true,0) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('cobalt-citrus-juicer','Cobalt citrus juicer','Kitchen','A deep blue citrus juicer with a raised center and a pouring spout.',null,0,1.02,null,'BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/cobalt-citrus-juicer.jpg", "alt": "Cobalt citrus juicer"}]'::jsonb,'blue',true,1) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('green-matcha-bowl','Green matcha bowl','Tea rituals','A wheel-thrown green matcha bowl with a pouring spout and visible throwing lines.',null,0,1.1,null,'BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/green-matcha-bowl-full.jpg", "alt": "Green matcha bowl, full view"}, {"src": "/products/green-matcha-bowl.jpg", "alt": "Green matcha bowl"}]'::jsonb,'butter',true,2) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('amber-slow-feeder','Amber slow feeder','For pets','A small-dog slow feeder with concentric rings in an amber and brown glaze.',null,0,1.67,'6 × 6 inches','BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/amber-small-dog-slow-feeder.jpg", "alt": "Amber slow feeder"}]'::jsonb,'peach',true,3) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('dark-glaze-slow-feeder','Dark glaze slow feeder','For pets','A small-dog slow feeder with concentric rings and a dark brown and green glaze.',null,0,1.1,'5.5 × 5.5 inches','BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/dark-glaze-small-dog-slow-feeder-front.jpg", "alt": "Dark glaze slow feeder"}, {"src": "/products/dark-glaze-small-dog-slow-feeder-angle.jpg", "alt": "Dark glaze slow feeder — alternate view"}]'::jsonb,'mint',true,4) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('blue-trinket-tray','Blue trinket tray','Around the home','A small, wavy-edged tray in blue and pale glazes for your everyday little things.',null,0,0.97,null,'BMX clay',null,'','[{"src": "/products/blue-small-trinket-tray.jpg", "alt": "Blue trinket tray"}]'::jsonb,'lilac',true,5) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('cream-green-slow-feeder','Cream & green slow feeder','For pets','A small-dog slow feeder with concentric rings and a contrasting cream and green glaze.',null,0,1.39,'6 × 6 inches','BMX clay','Dishwasher and microwave safe.','Slightly damaged at the bottom. Please review this condition note before purchasing.','[{"src": "/products/cream-green-small-dog-slow-feeder-front.jpg", "alt": "Cream & green slow feeder"}, {"src": "/products/cream-green-small-dog-slow-feeder-top.jpg", "alt": "Cream & green slow feeder — alternate view"}]'::jsonb,'butter',true,6) on conflict(slug) do nothing;
insert into public.products(slug,name,category,description,price_cents,stock,weight_lbs,dimensions,material,care,condition_note,images,tone,published,sort_order) values ('blue-garlic-grater','Garlic grater & spoon rest','Kitchen','A blue glazed garlic grater that doubles as a spoon rest.',null,2,0.46,null,'BMX clay','Dishwasher and microwave safe.','','[{"src": "/products/blue-garlic-grater-spoon-rest.jpg", "alt": "Blue garlic grater and spoon rest"}]'::jsonb,'blue',true,7) on conflict(slug) do nothing;
